### ISSUE TITLE
2.1.1 is not on packagist

### ISSUE THREAD

**Issue by chescos** [syntaxerrors/Steam#101]
Hey, could we get the release 2.1.1 on [Packagist](https://packagist.org/packages/syntax/steam-api) so that we can make it more accessible through composer?

**Comment by riddles8888** [comment]
@stygiansabyss You may need to go refresh via packagist. I am not a maintainer on that package so I cant look. Everything looks like it is configured fine on the github side. Not sure they the latest release missing.

**Comment by nicekiwi** [comment]
Yes, I goofed the release. the `composer.json` file needs to be updated with the new package version.

**Comment by nicekiwi** [comment]
I will push out v2.1.2 in a few hours which should contain all the correct release versions.

**Comment by chescos** [comment]
@nicekiwi Hey, any updates on this?

**Comment by nicekiwi** [comment]
@chescos yes! right, good call. new job, very distracted. All tests are passing so I see no reason not to release immediatly. :)

**Comment by nicekiwi** [comment]
Version [2.1.2](https://github.com/syntaxerrors/Steam/releases/tag/2.1.2) has been released.
