### ISSUE TITLE
[Tip]Retrieve Screenshots from appDetails()

### ISSUE THREAD

**Issue by m4aax16** [syntaxerrors/Steam#108]
Hello,

The default method dosn't retrieve screenshots of a game.
To get the images follow the steps : 

1. Open App.php file

"../vendor/syntax/steam-api/src/Syntax/SteamApi/Containers/App.php"

2. Replace the content with the code on pastebin : 

https://pastebin.com/JM5myhx2

What did i change ?

I have added two lines.
The class variable :
    public $screenshots;

 and this line on constructor :
$this->screenshots  = $this->checkIssetCollection($app, 'screenshots', new Collection());

Almost the same was done with Mac- & Linuxrequirements.

Happy coding 👍

**Comment by nicekiwi** [comment]
![Screenshot from 2021-01-24 14-38-49](https://user-images.githubusercontent.com/738975/105618932-f45c8c80-5e51-11eb-81f9-761571e0eae5.png)

Thanks for the tip! :D
