### ISSUE TITLE
steamID fetching issues

### ISSUE THREAD

**Issue by nicekiwi** [syntaxerrors/Steam#11]
it looks like in the functions to build to the URL to get steamId's from valves API; when more than one ID is given they are not being comma separated as thet should, but instead return this:

`&format=json&steamids%5B0%5D=76561197970526236&steamids%5B1%5D=76561197971704940&steamids%5B2%5D=76561197995389992&steamids%5B3%5D=76561198036102944`

Which returns an error. This is present in multiple functions.

I tried making a PR, but, i'm not sure how to fix everything. 

More than that, when multiple IDs are given to the __call function in Client.php, when checking for the ID32 to convert to ID64, it assumes there is only one ID is given, when a whole array might have been given. My solution was this: (strpos in your code has the needle and haystack around the wrong way)

    // there may be more than one steamId
			array_walk($this->steamId, function(&$id, $key)
			{
				if (strpos($v, ':') !== false) 
				{
					// Convert the id to all types and grab the 64 bit version
					return $this->convertToAll($this->steamId)[2];
				}
			});

And finally there is a limit of 100 steamId's that can be returned per request, which means that the Group I want to get player summaries from (400+ members), if I tried to get them with a single call, I'd only get 100. Could you array_chunk them into a loop, to make multiple requests of 100 each?

**Comment by stygiansabyss** [comment]
I already did the 100+ member bug in one of my recent commits.  So you should be good there once it gets a version tag.

The initial __call parameter was only ever intended for a singular steam id.  But since we have done so much to get the steam ids up to snuff, I'll add in your code.  Might as well just walk regardless.  Worse that happens is a quick operation to get back the 64 id anyway.

**Comment by nicekiwi** [comment]
ha, theres a mistake in the code I posted there too. $v is used in strpos instead of $id.

**Comment by stygiansabyss** [comment]
Had wondered where you were conjuring that variable in a closure.  But all is well.  I'll get it added soon as I can.

**Comment by stygiansabyss** [comment]
Quick question (sorry, been kind of hectic lately), which call could I use as an example of your first issue?  The steamids=ID repeating one.

**Comment by nicekiwi** [comment]
Uhh, Not entirly sure what you mean.

I was passing an array of steamIDs to the getPlayerSummeries() function.

**Comment by stygiansabyss** [comment]
Still doing some testing on this to make sure the array_walk works as expected.  Should have a new release out soon.

**Comment by stygiansabyss** [comment]
1.2.0 is tagged.  I'm going to close this.  Just comment or open a new one if I missed something or something doesn't work.
