### ISSUE TITLE
GetPlayerItems no longer works!

### ISSUE THREAD

**Issue by PlanetTheCloud** [syntaxerrors/Steam#115]
To get CSGO (App ID 730) item inventory with GetPlayerItem would result in "Method permanently disabled" error as this method is no longer supported and has since moved to https://steamcommunity.com/profiles/<id>/inventory/json/730/2/?l=english or https://steamcommunity.com/inventory/<id>/730/2?l=english

**Comment by nicekiwi** [comment]
:(
