### ISSUE TITLE
issue on install

### ISSUE THREAD

**Issue by daviday** [syntaxerrors/Steam#13]
Installed but missing packages, any help would be much appreciated. 
TIA

Steam needs to install these additional packages: 
	libgl1-mesa-dri:i386, libgl1-mesa-glx:i386
[sudo] password for david: 
...............................................................................
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-glx:i386 : Depends: libglapi-mesa:i386 (= 8.0.4-0ubuntu0.7)
E: Unable to correct problems, you have held broken packages.
Press return to continue:

**Comment by stygiansabyss** [comment]
Ahh, I see what happened.  Looks like you are trying to install steam itself on linux.  You would need to look to steam for that. This is simply a php package that talks to the steam API.

Sorry I couldn't help you.

**Comment by daviday** [comment]
No worries, I'm all over the place right now trying to get a few things to work in harmony. A lot more difficult than I had anticipated. 
Thanks man
