### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by vstyler96** [syntaxerrors/Steam#134]
I am trying to include in my APP, but it's laravel 9 app :(.

**Comment by Teakowa** [comment]
You can see the progress of Laravel 9 support at #126, and you can also use this PR branch to temporarily make your app works.

**Comment by nicekiwi** [comment]
Sorry for slow responses guys, but there is a `laravel9` branch you can try.

**Comment by chescos** [comment]
Hey, any news on a stable release for Laravel 9?

**Comment by starcevpro** [comment]
Please add

**Comment by nicekiwi** [comment]
Support for Laravel 9 has ended, but 3.0.0 now supports Laravel 10 and 11. 🎉
