### ISSUE TITLE
Update to Laravel 5

### ISSUE THREAD

**Issue by MatthewLilley** [syntaxerrors/Steam#15]
Call to undefined method [package] with Laravel 5

**Comment by stygiansabyss** [comment]
Yeah, it would do that.  It hasn't been moved to L5.  Still sitting on 4.2.

**Comment by MatthewLilley** [comment]
I was about to submit a pull request and then noticed you've updated it. Good stuff man.

**Comment by stygiansabyss** [comment]
:)  Ty
