### ISSUE TITLE
Container Player doesn't set properly some of the properties

### ISSUE THREAD

**Issue by FakeHeal** [syntaxerrors/Steam#23]
I'm not quite sure whether this is a problem or I'm not fully understanding the workflow of your package (if that's the case I'm **really** sorry about that, this is a really helpful package and I'm happy to use it).

The problem I'm facing, with a little bit of going through your code is:
Class `class Player extends BaseContainer`  you have a `__construct` which sets the information provided by Steam to your `Player` object. But what I found strange (when I didn't get few properties, though my profile is completely public) is that Steam response's keys are all lowercase:
![screenshot_2](https://cloud.githubusercontent.com/assets/1038697/8201022/2961ed48-14d5-11e5-82d3-1dba6b2f5a36.png)

If I change your code to:

```
$this->realName = $this->checkIssetField($player, 'realname');
$this->primaryClanId = $this->checkIssetField($player, 'primaryclanid');
$this->timecreated = $this->checkIssetField($player, 'timecreated');
$this->personaStateFlags = $this->checkIssetField($player, 'personastateflags');
$this->locCountryCode = $this->checkIssetField($player, 'loccountrycode');
$this->locStateCode = $this->checkIssetField($player, 'locstatecode');
```

I get the correct information. I'm really confused since your example outputs is the same as mine without, apparently, those modifications.

Regarding the `loccityid`, a method should be implemented to fetch correct users locations since Steam uses
>An internal code indicating the user's city of residence.  - [Steam Web API](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29)

In [this repository](https://github.com/Holek/steam-friends-countries) there's a JSON file which has all of the locations that Steam uses.

So why did I need to make those modifications? Am I doing something wrong?

Cheers,
Ivanka Todorova

**Comment by stygiansabyss** [comment]
Let me take a look at this today and see.  It's possible things have changed in the API.  I'll test and let you know.

**Comment by stygiansabyss** [comment]
This is fixed now.  You can see how the new player container will look in the examples folder.
