### ISSUE TITLE
Is it possible to get an achievements' image?

### ISSUE THREAD

**Issue by pfeiferchristopher** [syntaxerrors/Steam#24]
Hello,

First off, I love the package works great for me.

Secondly, I was wondering if it was possible for to get the image location for an achievement? Like the ones shown on Steam Community for each achievement.

Thanks!

**Comment by stygiansabyss** [comment]
So, from the base API call this is not possible.  However, there is a secondary API call that I didn't know existed that will get the achievement icon url.  I will work on adding this in.

**Comment by stygiansabyss** [comment]
This has been added to master.  I will tag a release once I get the back port to L4 done.

**Comment by stygiansabyss** [comment]
https://github.com/syntaxerrors/Steam/blob/master/examples/user/stats/GetPlayerAchievements.txt

For reference on the new return object.

**Comment by pfeiferchristopher** [comment]
Damn such a quick response! Thanks now I can show the achievements much better.

**Comment by stygiansabyss** [comment]
I'd love to see what you do with it.  If you'd be willing to send a link.

**Comment by pfeiferchristopher** [comment]
http://www.gamejerks.net request an invitation and I'll send one.
