### ISSUE TITLE
L5.2 Class 'Guzzle\Http\Client' not found

### ISSUE THREAD

**Issue by Netifriik** [syntaxerrors/Steam#32]
Fresh install of Laravel 5.2. Trying to get player summary.

**Comment by Netifriik** [comment]
Made some changes in `Client.php`
```
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\Exception\ClientErrorResponseException;
use GuzzleHttp\Exception\ServerErrorResponseException;
```
And changed some `get()` functions to `request()` but now I'm getting:

Client error: `HTTP://API.STEAMPOWERED.COM/ISTEAMUSER/GETPLAYERSUMMARIES/V0002/?STEAMIDS=76561198038526790&KEY=2559E5641E08544DD88A161C9D4741CD&FORMAT=JSON http://api.steampowered.com/` resulted in a `400 Bad Request` response:

**Comment by Netifriik** [comment]
Ok I finally got it working by adding
`use GuzzleHttp\Psr7\Request;`
and by changing `get()` functions to this:
`$request = new Request('GET', $steamUrl . '?' . $parameters);`

**Comment by riddles8888** [comment]
@stygiansabyss

**Comment by stygiansabyss** [comment]
I will look into tagging new releases for 5.1 and 5.2

**Comment by FavreNicolas** [comment]
On my laravel http://imgur.com/vvimjx2
Server running on ubuntu 15.10 php5

**Comment by Netifriik** [comment]
@FavreNicolas see this pull request for fixes https://github.com/syntaxerrors/Steam/pull/35

**Comment by Mahmoudz** [comment]
Just installed the package and I'm getting this error now! (I'm on L5.1). I'll try to fix it and make a PR very soon.
