### ISSUE TITLE
ConvertToID64 has cast to integer, with todays steamid are over integer boundary!

### ISSUE THREAD

**Issue by reaby** [syntaxerrors/Steam#33]
Hi,
And thanks for very nice library, i had problems with steamid class.
What I believe, is that the integer cast at line 81 @ SteamId.php will go over integer boundaries
        $this->formatted->{self::$ID64} = (int) $formatted;

I think it should be written without the integer cast:
	$this->formatted->{self::$ID64} = $formatted;

With this little modification i was able to recieve the right SteamID64 for my need.

Hopefully you can fix soon.

**Comment by stygiansabyss** [comment]
Updated the L5 and L4 branches with this.  It may end up returning a string currently.  I will check into it when I have more time and find a long term fix if needed.

Laravel 4: 1.2.6
Laravel 5: 2.0.5

**Comment by stygiansabyss** [comment]
Yeah, it converts it to a string.  I cannot find any way around this (even with the gmp library since it changes the number).
