### ISSUE TITLE
Undefined property: stdClass::$PS

### ISSUE THREAD

**Issue by Nenji** [syntaxerrors/Steam#39]
Hey!
I'm trying to get all friends w/ this code.

`$playerFriends = \Steam::user($player->steamID)->GetFriendList();`
and that's what I get:

> ErrorException in C:\Websites\csgoglobe\vendor\syntax\steam-api\src\Syntax\SteamApi\Containers\Player.php line 85:
> Undefined property: stdClass::$PS

I don't know what I did wrong.
Regards
nenji

btw. It would be nice, if you can add the fully code of every method + how to use it.

**Comment by stygiansabyss** [comment]
Which version are you using?  Line 85 just sets a variable to an stdClass object.

**Comment by Nenji** [comment]
@stygiansabyss I'm using 2.0 (version)

**Comment by stygiansabyss** [comment]
Alright, firstly, set the version to `^2.0`.  That will keep you on the 2.0 track and get any updates i make that wont break anything.

Regarding Guzzle, this has been a problem for quite some time with a few people.  I do actually have free time Friday, which I do plan to fix up this package.  To fix this, wait a few minutes then run `composer update syntaxerrors/steam-api`.  Once you see it have `2.0.6` in the yellow text, you have the latest version.

**Comment by stygiansabyss** [comment]
Also, regarding your comment about documenting every method.  Is that not done on the [readme](https://github.com/syntaxerrors/Steam/blob/master/README.md)?
