### ISSUE TITLE
Requiring 2.0.7 pins laravel to 5.x.0

### ISSUE THREAD

**Issue by thorerik** [syntaxerrors/Steam#40]
When I pinned syntax/steam-api to 2.0.7, Laravel got force downgraded:
```
± composer update
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing laravel/framework (v5.3.2)
  - Installing laravel/framework (v5.3.0)
    Downloading: 100%         

  - Installing nukacode/database (1.0.2)
    Downloading: 100%         

  - Removing syntax/steam-api (2.0.6)
  - Installing syntax/steam-api (2.0.7)
    Downloading: 100% 
```
which I'd say is highly undesirable.

**Comment by stygiansabyss** [comment]
The newest version allows 5.0, 5.1, 5.2 or 5.3.  In your composer.json are you specifically requiring `"laravel/framework": "^5.3"`?

**Comment by thorerik** [comment]
we specify "laravel/framework": "5.3.*"

**Comment by stygiansabyss** [comment]
Yeah, I started up a new install of 5.3 and it complained about the versions.  I have created 2.0.8 which sets the version back to `^5.0`.  So anything 5.0-<6.0 should be fine.

**Comment by stygiansabyss** [comment]
Let me know if this fixes things for you.

**Comment by thorerik** [comment]
yup, now it's good :+1:
