### ISSUE TITLE
Check if steamID exists if not return null instead of a exception?

### ISSUE THREAD

**Issue by Nenji** [syntaxerrors/Steam#41]
Hey!
Is it possible to return null instead of Exception?

## Example
Code
```
  public function getWeapons($steamID) {
    $stats = \Steam::userStats('asdpw3s0')->GetUserStatsForGame(730, true)->stats;
```
   Output:
![Exception](https://i.gyazo.com/58042d4950ebf8ca6920e79acd634d11.png)

Is it possible to check if the user exists?
Regards

**Comment by stygiansabyss** [comment]
Not really. That would an extra step on all uses of these methods. I will look into it though.

**Comment by thorerik** [comment]
a more descriptive exception would be desired imo rather than null. Null opens a lot of avenues where you act upon the return value.

IMO it's better to halt the execution than return a (potentially) valid response for invalid input.

**Comment by stygiansabyss** [comment]
I looked into the code and found that I was already running the ID convert on IDs that had a colon in them.  That would catch ID32 and ID3 versions of an ID.  I have changed this to also run on ID64 possible steam IDs which means that any ID submitted gets checked for validity and returns the exception when invalid.

```php
$steam->user($this->bad)->GetPlayerBans();
```

![screen shot 2016-08-29 at 8 19 47 am](https://cloud.githubusercontent.com/assets/4187442/18052682/623b0c76-6dc1-11e6-9644-9db4e2d6b3f7.png)

**Comment by stygiansabyss** [comment]
2.0.9 tagged for use.

**Comment by Nenji** [comment]
@stygiansabyss thanks! :)

**Comment by stygiansabyss** [comment]
Use a try catch to determine if it doesn't exist would be my suggestion here.

**Comment by Nenji** [comment]
@stygiansabyss It's not working.
```
  public function getWeapons($steamID) {
    try {
      $stats = \Steam::userStats($steamID)->GetUserStatsForGame(730, true)->stats;
    } catch (Exception $ex) {
      return json_encode(['validate' => false, 'response' => 'NOT VALID STEAMID']);
    }
```
That's what I get:
![^^](https://i.gyazo.com/3b061d733dac838a9ac8c4a5efbbf7e9.png)

**Comment by stygiansabyss** [comment]
Use \Exception?

**Comment by Nenji** [comment]
@stygiansabyss my bad. Working now. Would be nice, if you can close this issue. :heart_eyes:

**Comment by stygiansabyss** [comment]
Sure thing. Glad I could help
