### ISSUE TITLE
Get User Inventory

### ISSUE THREAD

**Issue by xDestinatioNx** [syntaxerrors/Steam#49]
Hi, I want to display the users inventory but I didn't find something to do this.
By searching the project files I found class `Item` with `GetPlayerItems` in it but I don't know how to use it.

**Comment by stygiansabyss** [comment]
It is not finished.  It was something that was requested but that I have never used.  I have no clue when it will be finished.

**Comment by xDestinatioNx** [comment]
Is it a lot of work to implement it?

**Comment by stygiansabyss** [comment]
It is not well documented like most of the Steam API.  Combine that with the lack of a use I have for it and it makes it a bit more tricky.  I am not sure if this will ever get added completely.  But I may take another stab shortly.

**Comment by stygiansabyss** [comment]
I have added the method for GetPlayerItems.  It is not documented or tested so it will not be tagged as of yet.  If you want this functionality, point to dev-master for the time being.

Alternately, if you want to add tests, examples and docs in the readme I will merge them and tag a new release.

**Comment by nicekiwi** [comment]
I'll have a look.

**Comment by nicekiwi** [comment]
Implemented in #75 PR.
