### ISSUE TITLE
Incorrect AppDetails

### ISSUE THREAD

**Issue by 73cn0109y** [syntaxerrors/Steam#52]
When trying to get details for some a games multiplayer version, it returns the data for the main game.

For example, when trying to get details for `Call of Duty: Advanced Warfare - Multiplayer` with an appId of `209660`, It returns the data for `209650` which is `Call of Duty: Advanced Warfare`.

Steam appears to be doing this in the background when hitting the `appDetails` store endpoint (using`Steam::app()->addDetails($appIds)`) , but you should probably find a way to get the correct info. I'm unsure how their client, or other websites (like steamdb) get the correct information.

This also happens for;
`209170` -> `209160` (Call of Duty: Ghosts [- Multiplayer])

**Comment by stygiansabyss** [comment]
What method are you calling?  Just appDetails?

**Comment by 73cn0109y** [comment]
> What method are you calling?  Just appDetails?

Yeah

**Comment by Deazl** [comment]
This is Steams fault. The multiplayer part of this game is bound to the main game and thats why it doesn't have a dedicated shop site or custom app details. It just returns everything from the main game.

**Comment by stygiansabyss** [comment]
Closing this as it seems solved.
