### ISSUE TITLE
Use Laravel Collections instead of the Nukacode Collections

### ISSUE THREAD

**Issue by Kovah** [syntaxerrors/Steam#54]
I just recently struggled with the Nukacode Collections that are returned for all Steam API responses because I needed some features that are provided by Laravel Collections but not by the Nukacode ones. Had to work around it by passing the collection to a new Laravel collection instead.

Is there a specific reason to stay with the Nukacode collections? If not I would really like to switch over.

**Comment by Kovah** [comment]
Ah, never mind. The glorious syntax error lead to not working collections.

**Comment by stygiansabyss** [comment]
I prefer them over standard collections. They extend the laravel ones so
anything laravel could do they should be able to do as well.
