### ISSUE TITLE
Returns incorrect steam ids

### ISSUE THREAD

**Issue by SomePanns** [syntaxerrors/Steam#57]
This does not look right!

```
"steamIds": {
                "id32": "STEAM_1:-1:-38280597906391040",
                "id64": "2147483647",
                "id3": "[U:1:-76561195812782081]",
                "communityId": "STEAM_1:-1:-38280597906391040",
                "steamId": "2147483647"
            },
```

**Comment by stygiansabyss** [comment]
You are correct.  The math looks like it went weird on you.  Could you add more detail on how you get this?  Is it just passing that id64 to the converter?

**Comment by nicekiwi** [comment]
@SomePanns appears inactive. Please re-open if you can provide any detail.
