### ISSUE TITLE
GetRecentlyPlayedGame[header] Has been redirected

### ISSUE THREAD

**Issue by AGDholo** [syntaxerrors/Steam#58]
GetRecentlyPlayedGame[header] Has been redirected to http://store.steampowered.com/

**Comment by stygiansabyss** [comment]
Could you elaborate on this?  Is the call failing now?

**Comment by AGDholo** [comment]
Sorry,i have not writing code that using this package for long time,pls close the issue or wait some as same as the error who are active.

**Comment by nicekiwi** [comment]
I can't replicate this, closing.

![image](https://user-images.githubusercontent.com/738975/53706725-8b03b700-3e90-11e9-9688-ac3304b8be75.png)
