### ISSUE TITLE
Support getting SteamID from CommunityID

### ISSUE THREAD

**Issue by nicekiwi** [syntaxerrors/Steam#6]
This (Wonderful <3) app uses the communityID as the SteamID, it'd be great to have a built-in function to convert from the communityID to the steamID and back again and include the output in **GetPlayerSummaries**. 

As the steamID is whats used in allot of the SouceMod plugins.

Documented here:
https://developer.valvesoftware.com/wiki/SteamID#Steam_ID_as_a_Steam_Community_ID

Thanks :)

**Comment by stygiansabyss** [comment]
I will look into adding this support as soon as I can.

**Comment by nicekiwi** [comment]
This is what I made to do it for now:

    public function convertCommunityIdToSteamId(int $id)
	{
		$x = ($id - 76561197960265728) / 2;
		return 'STEAM_0:' . is_float($x) . ':' . (int)$x; 
	}

	public function convertSteamIdToCommunityId(string $id)
	{
		$x = explode(':', $id);
		return (string) ($x[2] * 2) + 76561197960265728 + $x[1];
	}

This as a reference also:
http://www.sythe.org/archives/583029-how-convert-communityid-steamid-ves-versa.html

**Comment by stygiansabyss** [comment]
If you had made this a pull request, I would have added it in.  Those methods look fine to me.  Adding them in now.

**Comment by stygiansabyss** [comment]
Once I finish the other request you made I will create a release.  These methods have been added along with a helper in Client->__call to auto convert steam IDs to community IDs when present.

**Comment by nicekiwi** [comment]
:+1:

**Comment by nicekiwi** [comment]
You are adding support for both the SteamID and CommunityID to be returned in **GetPlayerSummaries**?

**Comment by stygiansabyss** [comment]
Added, along with doc and example updates.

**Comment by nicekiwi** [comment]
Hey awesome, but technically speaking the ID's are around the wrong way :)

**SteamID32**: STEAM_0:1:6587177
**SteamID64/CommunityID**: 76561197973440083

But as your whole package is based on the 64bit ID, could be a bother to change.

And there's the more recent one that you could still add here also:

**steamID3**: [U:1:13174355]

There's some docs on that here: 
http://forums.steampowered.com/forums/showthread.php?t=3261998

The conversion looks something like:
STEAM_0:A:B
[U:1:B*2+A]

Which would be cool to have too for future proofing.

**Comment by nicekiwi** [comment]
Actually, with the names you've given those converters and the names you've given to the steamIDs it will get quite confusing.

**Comment by stygiansabyss** [comment]
I will be running through and fixing these, but it is a breaking change so it would technically be version 2.

**Comment by stygiansabyss** [comment]
Going to change your method names a bit.

convert<from>To<desired>

fomr and desired can be ID64, ID32 and ID3

**Comment by stygiansabyss** [comment]
Pushed to master.  Docs have been updated to help explain the method that is now available.
