### ISSUE TITLE
Example of php usage

### ISSUE THREAD

**Issue by rafal-olszewski** [syntaxerrors/Steam#60]
Could you please provide PHP example on how to use it ? I'm kind of new to Laravel, and I would like to get user info like, avatar, steam name, url etc. via his steam id 64 which I've got.

**Comment by stygiansabyss** [comment]
Im not sure i understand you here.  The readme has tons of documentation on how to use the available methods.

**Comment by stygiansabyss** [comment]
Closing as this seems solved
