### ISSUE TITLE
How to convert NEWS to proper HTML format?

### ISSUE THREAD

**Issue by pastuh** [syntaxerrors/Steam#63]
Hello, i get only Json format.

> 0 => {#394 ▼
    +"gid": "2149763711086575625"
    +"title": "Patch Notes 1.11.2 - HOTFIX"
    +"url": "http://store.steampowered.com/news/externalpost/steam_community_announcements/2149763711086575625"
    +"is_external_url": true
    +"author": "EW_Graham"
    +"contents": "http://cdn.edgecast.steamstatic.com/steamcommunity/public/images/clans/27000850/d8117d4ab90a185d26d0966fdbb1b1f97d92ff77.png Hello Hunters, Today we are cherry  ▶"
    +"feedlabel": "Community Announcements"
    +"date": 1505898417
    +"feedname": "steam_community_announcements"
    +"feed_type": 1
    +"appid": 518790

Can someone suggest how change to: XML ?

I want to get HTML tags. Thanks for any info :)

**Comment by stygiansabyss** [comment]
Seems I left the return type as protected.  Not sure if it would work anyway.  But feel free to change it manually in your copy of the code.  Its in the Client.php class.  If it works, feel free to make a pull request.

**Comment by stygiansabyss** [comment]
Closing this as it seems finished
