### ISSUE TITLE
Troubles calling Steam class.

### ISSUE THREAD

**Issue by TheConsciousness** [syntaxerrors/Steam#65]
When calling:
`$news = Steam::news()->GetNewsForApp($appId, 5, 500)->newsitems;`

I get:
> PHP Fatal error:  Uncaught Error: Class 'Steam' not found in /index.php:28\nStack trace:\n#0 {main}\n  thrown in index.php

I am not having any issues with any other Laravel/Composer vendors. Have you seen this before, or know what the issue may be?

**Comment by stygiansabyss** [comment]
Did you add it as a facade?

**Comment by TheConsciousness** [comment]
I believe I did:
![image](https://user-images.githubusercontent.com/14192161/34323450-bb72ed8c-e817-11e7-945d-231e2c0c0089.png)

**Comment by stygiansabyss** [comment]
That's the service provider. Check the aliases section

**Comment by TheConsciousness** [comment]
Sorry about that:

Syntax/SteamApi/SteamApiServiceProvider


```
 'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
    ],
```

**Comment by stygiansabyss** [comment]
Add the steam facade there

**Comment by TheConsciousness** [comment]
Roger that,
Would it be?:
`'Steam' => Syntax\SteamApi\SteamApiServiceProvider\Steam::class,`

**Comment by stygiansabyss** [comment]
No, you would set Steam to the steam facade class

**Comment by TheConsciousness** [comment]
Sorry, new to facades. :(
Am I close?:
`'Steam' => Syntax\SteamApi\Facades\SteamApi::class,`

**Comment by stygiansabyss** [comment]
That should work

**Comment by TheConsciousness** [comment]
:( Still getting:
`PHP Fatal error:  Uncaught Error: Class 'Steam' not found in ...`

**Comment by stygiansabyss** [comment]
Can you show me the whole class you are calling it in?

**Comment by TheConsciousness** [comment]
I currently have a php file in my laravel/public folder with:

`<?php
  require_once '../vendor/autoload.php';
  use Jumbojett\OpenIDConnectClient;
    $steam = new Steam();
?>
`
For testing purposes. Perhaps I'm too confused with the whole laravel/composer thing.

**Comment by stygiansabyss** [comment]
Yeah. Place the steam code in a controller. In laravel we don't do much php
code in the public folder.

**Comment by TheConsciousness** [comment]
Tried reinstalling Laravel, creating a new laravel project and then re-requiring SteamApi. Added the class and followed your readme instructions. Moved the test php file into the /app folder. Getting the same error from that location. :(

**Comment by stygiansabyss** [comment]
You need to look at laravel docs on getting started

**Comment by TheConsciousness** [comment]
Will do. Thank you for being so helpful and prompt.

**Comment by stygiansabyss** [comment]
Np. Hope it works out for you

**Comment by hassamali** [comment]
@stygiansabyss 

in providers 
`Syntax\SteamApi\SteamApiServiceProvider::class,`

use this in alias  
`'Steam' => Syntax\SteamApi\SteamApiServiceProvider::class,`

and when you are using Steam class in controller use namespace top of that file like this
`user Steam;`

and you are good to go.

**Comment by stygiansabyss** [comment]
Closing as it seems solved.
