### ISSUE TITLE
Additional attribute by feed_type ?

### ISSUE THREAD

**Issue by pastuh** [syntaxerrors/Steam#66]
Hello.
How i can add additional attribute/parameter, to check feed_type.
My news should be only from specific appid and with feed_type 1

Issue: I got news from other game portal.

+"feedlabel": "Rock, Paper, Shotgun"
+"date": 1514919601
+"feedname": "rps"
+"feed_type": 0
+"appid": 550
  
For now i fixed like this, but i hope for better solution

>        foreach($news as $key=>$new) {
>           if($new->feed_type == 0){
>              unset($news[$key]);
>           }
>        }

**Comment by stygiansabyss** [comment]
What call are you using to get this?

**Comment by pastuh** [comment]
$news = Steam::news()->GetNewsForApp($appID, 21)->newsitems;

**Comment by stygiansabyss** [comment]
So, that method in this code base just returns what Steam gives us raw.  No transforming of the data happens.  If you want, you could make a pull request to convert it to a collection, then you could just do a filter.

```
$news->whereNot('feed_type', 0);
```

**Comment by nicekiwi** [comment]
I'm not entirly convinced, it's as easy as `$news = collect($news)->whereNot('feed_type', 0);`

**Comment by nicekiwi** [comment]
![image](https://user-images.githubusercontent.com/738975/66540543-b538f800-eb88-11e9-8b3d-e9c8d08b42f7.png)
 
Though now that I've done it just to show how easy it is.. I may as well just commit the change.

**Comment by nicekiwi** [comment]
Actually I don't see the benifet of this when it's so easy convert anyway.
