### ISSUE TITLE
Retrieving appDetails for multiple appIds fails

### ISSUE THREAD

**Issue by chescos** [syntaxerrors/Steam#69]
I tried to call `appDetails` with an array of app IDs as parameter, e.g:

```
$appDetails = Steam::app()->appDetails([730, 32330]);
```

Result:

```
Client error: `GET http://store.steampowered.com/api/appdetails/?appids%5B0%5D=730&appids%5B1%5D=32330&key=*REMOVED*&format=json` resulted in a `400 Bad Request` response
```

A call that works:

```
http://store.steampowered.com/api/appdetails/?appids=730,32330&filters=price_overview
```

Note that it only works when appending `filters=price_overview`.

**Comment by chescos** [comment]
Okay, I checked again and as it seems the correct usage would be:

```
$appDetails = Steam::app()->appDetails('730,32330');
```

The issue is probably on Steam's side because the request still fails:

```
Client error: `GET http://store.steampowered.com/api/appdetails/?appids=730%2C32330&key=*REMOVED*&format=json` resulted in a `400 Bad Request` response
```

Still, the request works when appending `filters=price_overview` to the query. Would it be possible to add an optional second `$filters` parameter to the `appDetails` method?

**Comment by stygiansabyss** [comment]
This is possible, but I wont have time to add this for a while.  If you would like to do a pull request, that would be great!

**Comment by nicekiwi** [comment]
Does this request actually return anything meaningful when it does work? As far as I can see it only returns pricing details for one of the appIDs

**Comment by nicekiwi** [comment]
When it's easy enough to loop the apps you want data from I don't think providing it intenrally is useful. Plus I can't get any useful data out for both apps.
