### ISSUE TITLE
GetFriendList

### ISSUE THREAD

**Issue by dig** [syntaxerrors/Steam#70]
Any chance you could include a new parameter for the GetFriendList method so that we can skip the GetPlayerSummaries pass through? Running GetPlayerSummaries for every friend is quite slow and I'd just like to get a list of steamids not each friends profile.

**Comment by stygiansabyss** [comment]
This could be added.  If you want it soon (i wont have time to do it anytime soon), you could submit a PR and we'd be happy to merge it.

**Comment by nicekiwi** [comment]
Fixed by #85

**Comment by nicekiwi** [comment]
Included in v2.0.15.
