### ISSUE TITLE
New in Laravel: How i can implement this?

### ISSUE THREAD

**Issue by burhan-kun** [syntaxerrors/Steam#71]
Hello,

i have do all, what u say in the Documentation. Now i will use it in my Controller and become this error:

(1/1) FatalThrowableErrorClass 'App\Http\Controllers\Steam' not found
--
 
I try:
use Syntax\SteamApi\SteamApiServiceProvider;

But that dont works? What must i do?

**Comment by stygiansabyss** [comment]
Import the facade, not the service provider.

**Comment by burhan-kun** [comment]
what i must write in the controller? use Steam;?

**Comment by stygiansabyss** [comment]
Honestly, I feel like you need to spend a little more time learning laravel.  You need to know the basics before just jumping in.  The documentation at laravel.com/docs is amazing.

**Comment by burhan-kun** [comment]
Thank you :-)
