### ISSUE TITLE
Aliases not working [Laravel v5.8.7]

### ISSUE THREAD

**Issue by DubStepMad** [syntaxerrors/Steam#86]
I have checked the package aliases and compared it with the version of Laravel I am using which is 5.8.7 and doesn't seem to match the requirements in which the aliases is assigned.

https://laravel.com/docs/5.8/packages

**Comment by nicekiwi** [comment]
Are the alias' actually not working in 5.8? 

The alias is still registered by the service provider to maintain backwards compatibility with Laravel < 5.5. The methods to do so are not deprecated; so it *should* be working still.

Though I suppose updating the composer.json would not harm older versions..

**Comment by DubStepMad** [comment]
Sorry for the long wait.

Yes they don't work as I have tried multiple times and on a fresh project just to make sure it wasn't a mistake I was making.

**Comment by nicekiwi** [comment]
OK, will have a look.

**Comment by nicekiwi** [comment]
@DubStepMad can you please share your repo/code?

I've tested with "v5.8.12" and it works as expected.

**Comment by DubStepMad** [comment]
> @DubStepMad can you please share your repo/code?
> 
> I've tested with "v5.8.12" and it works as expected.

Sorry for the long reply, I have since removed this from my project as I couldn't get it to work as expected. This might be a personal issue as I am new to Laravel.
