### ISSUE TITLE
Some profiles do not have profilestate defined

### ISSUE THREAD

**Issue by hydrarulz** [syntaxerrors/Steam#9]
This is a bit weird.

A profile I found does not have the property profilestate defined so when I tried to run ->GetFriendList('friend')

I got an exception. For example this happens for the profile steamId:76561198053558284
Not sure if the best solution is changing in the file
**Steam/src/Syntax/SteamApi/Containers/Player.php** at **line #54**

> $this->profileState             = @$player->profilestate;

I guess the strangest thing is the profile having a different structure.

**Comment by stygiansabyss** [comment]
What is the exception you are getting?  Also, I sent you an invite to slack if you need to get ahold of me.

**Comment by hydrarulz** [comment]
I don't have the project opened at the moment but the property is not present in the $player object.

**Comment by stygiansabyss** [comment]
Camel case.  "profileState"

**Comment by hydrarulz** [comment]
Ok, I must paste the exception here. The problem is not in my code, is in the library itself.

> [2015-01-08 11:34:56] probook.ERROR: exception 'ErrorException' with message 'Undefined > property: stdClass::$profilestate' in /usr/share/nginx/GameWorld/vendor/syntax/steam-> api/src/Syntax/SteamApi/Containers/Player.php:54

Please check for the steamId that I specified above

**Comment by stygiansabyss** [comment]
It is telling you that "profilestate" is not a valid property.  It is correct.  Use "profileState".  Notice that the S is capitalized.

**Comment by hydrarulz** [comment]
Dude, I don't get to use the property profileState. This happens when the data is loaded from the API. I will post you the code with the problem. Where it happens. 
Please take a look at the code and test with the steamId I provided and just **load** the data. You don't get to use any properties, it crashes when I get the friends list, not after.

It happens when I run this
> $friends = Steam::user($SteamId)->GetFriendList('friend');

Not when I loop over the friends and try to use the incorrect property. And it only happens with some profiles not all.

Also if you would look at the line with the problem you would realize the problem is when the object is created, not when it is accessed. This is from the file **Steam/src/Syntax/SteamApi/Containers/Player.php**
>	public function __construct($player)
>	{
>		$this->steamId                  = $player->steamid;
>		$this->steamIds                 = (new Id((int)$this->steamId));
>		$this->communityVisibilityState = $player->communityvisibilitystate;
>		$this->profileState             = $player->profilestate;
>		$this->personaName              = $player->personaname;
>		$this->lastLogoff               = date('F jS, Y h:ia', $player->lastlogoff);
>		$this->profileUrl               = $player->profileurl;
>		$this->avatar                   = $this->getImageForAvatar($player->avatar);
>		$this->avatarMedium             = $this->getImageForAvatar($player->avatarmedium);
>		$this->avatarFull               = $this->getImageForAvatar($player->avatarfull);
>		$this->avatarUrl                = $player->avatar;
>		$this->avatarMediumUrl          = $player->avatarmedium;
>		$this->avatarFullUrl            = $player->avatarfull;
>		$this->personaState             = $this->convertPersonaState($player->personastate);
>		$this->personaStateId           = $player->personastate;
>		$this->primaryClanId            = $this->checkIssetField($player, 'primaryClanId');
>		$this->timecreated              = $this->checkIssetField($player, 'timecreated');
>		$this->personaStateFlags        = $this->checkIssetField($player, 'personaStateFlags');
>		$this->locCountryCode           = $this->checkIssetField($player, 'locCountryCode');
>		$this->locStateCode             = $this->checkIssetField($player, 'locStateCode');
>		$this->locCityId                = $this->checkIssetField($player, 'locCityId');
>	}
 
Line #54 is
>		$this->profileState             = $player->profilestate;

Do you understand what I am saying?

**Comment by stygiansabyss** [comment]
I truly do not.  I have run the command with your steam Id and I get a proper response.  The constructor is not wrong.  I have changed profilestate to profileState to be more readable since it is two words being joined together.

```
Steam Id: 76561198053558284
Array
(
    [0] => Syntax\SteamApi\Containers\Player Object
        (
            [steamId] => 76561197987217337
            [steamIds] => Syntax\SteamApi\Containers\Id Object
                (
                    [id32] => STEAM_1:1:13475804
                    [id64] => 76561197987217337
                    [id3] => [U:1:26951609]
                    [communityId] => STEAM_1:1:13475804
                    [steamId] => 76561197987217337
                )

            [communityVisibilityState] => 3
            [profileState] => 1
            [personaName] => gooby pls
            [lastLogoff] => January 1st, 2015 11:46pm
            [profileUrl] => http://steamcommunity.com/profiles/76561197987217337/
            [avatar] => 
            [avatarMedium] => 
            [avatarFull] => 
            [avatarUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/05/058204d6327255c745297ad35e2c987609d7856f.jpg
            [avatarMediumUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/05/058204d6327255c745297ad35e2c987609d7856f_medium.jpg
            [avatarFullUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/05/058204d6327255c745297ad35e2c987609d7856f_full.jpg
            [personaState] => Offline
            [personaStateId] => 0
            [realName] => 
            [primaryClanId] => 
            [timecreated] => 1167760214
            [personaStateFlags] => 
            [locCountryCode] => 
            [locStateCode] => 
            [locCityId] => 
        )

    [1] => Syntax\SteamApi\Containers\Player Object
        (
            [steamId] => 76561198073683885
            [steamIds] => Syntax\SteamApi\Containers\Id Object
                (
                    [id32] => STEAM_1:1:56709078
                    [id64] => 76561198073683885
                    [id3] => [U:1:113418157]
                    [communityId] => STEAM_1:1:56709078
                    [steamId] => 76561198073683885
                )

            [communityVisibilityState] => 3
            [profileState] => 1
            [personaName] => iNom
            [lastLogoff] => May 27th, 2013 07:41pm
            [profileUrl] => http://steamcommunity.com/id/jimboze/
            [avatar] => 
            [avatarMedium] => 
            [avatarFull] => 
            [avatarUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb.jpg
            [avatarMediumUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_medium.jpg
            [avatarFullUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/fe/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg
            [personaState] => Offline
            [personaStateId] => 0
            [realName] => 
            [primaryClanId] => 
            [timecreated] => 1350499924
            [personaStateFlags] => 
            [locCountryCode] => 
            [locStateCode] => 
            [locCityId] => 
        )

    [2] => Syntax\SteamApi\Containers\Player Object
        (
            [steamId] => 76561197999078519
            [steamIds] => Syntax\SteamApi\Containers\Id Object
                (
                    [id32] => STEAM_1:1:19406395
                    [id64] => 76561197999078519
                    [id3] => [U:1:38812791]
                    [communityId] => STEAM_1:1:19406395
                    [steamId] => 76561197999078519
                )

            [communityVisibilityState] => 3
            [profileState] => 1
            [personaName] => Eugennic
            [lastLogoff] => December 18th, 2011 12:44am
            [profileUrl] => http://steamcommunity.com/profiles/76561197999078519/
            [avatar] => 
            [avatarMedium] => 
            [avatarFull] => 
            [avatarUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/eb/ebe49f63267a3c4ab4ed377d80bbd3f32449337f.jpg
            [avatarMediumUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/eb/ebe49f63267a3c4ab4ed377d80bbd3f32449337f_medium.jpg
            [avatarFullUrl] => http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/eb/ebe49f63267a3c4ab4ed377d80bbd3f32449337f_full.jpg
            [personaState] => Offline
            [personaStateId] => 0
            [realName] => 
            [primaryClanId] => 
            [timecreated] => 1212776597
            [personaStateFlags] => 
            [locCountryCode] => 
            [locStateCode] => 
            [locCityId] => 
        )

)
```

**Comment by nicekiwi** [comment]
@stygiansabyss is correct, I get the same result. profileState **IS** defined and in this case is `(int) 1` for each ID.

**Comment by stygiansabyss** [comment]
Marking this as closed.  If you have any more issues with this, please let me know.  As it stands, two people are getting the same results and they are showing as correct.
