### ISSUE TITLE
Laravel 6.0+ Support

### ISSUE THREAD

**Issue by ShadowRanger** [syntaxerrors/Steam#93]
This package does not seem to support Laravel 6.0 and above. Could you please add this support if possible?

**Comment by ShadowRanger** [comment]
94

**Comment by nicekiwi** [comment]
Once tests are working reliably I'll push out a lease to support laravel 6.

**Comment by nicekiwi** [comment]
v2.1.1 has been released and supports Laravel 5.8+.
